### ISSUE TITLE
How to use with show action instead of index

### ISSUE THREAD

**Issue by jpatel** [jasondew/data_table#17]
Hi, 
I am trying to use this gem. I want to display data table for show action instead of index action. 
For example,
class Post
 has_many :comments
end

class Comment
belongs_to: post
end

////   Post controller
def shows
////  business logic
comments = @post.comments
respond_to do |format|
      format.html
      format.json  do
        render(:json => Post.for_data_table(@comments, %w(... ), %w(...)) do |comment|
          ["<%= link_to(comment.id, comment_path(comment)) %>", .....]
        end )
      end
    end
end

I get NoMethodError (undefined method `for_data_table' for class.

Can you please provide documentation or any suggestion how to use it?
Thanks,

**Comment by jasondew** [comment]
Hi @jpatel!

Can you tell me what version of Rails you're using? Also, I would highly recommend using the <a href="https://github.com/jasondew/data_table/tree/next">`next` branch</a>. I'm working on finishing up version 2 and that's where the work is happening. The API is a bit different, but it in your case it would go something like this:

```ruby
def show
  respond_to do |format|
    format.html
    format.json { render json: data_table }
  end
end

private

def data_table
  DataTable context: self,
            data: @post.comments,
            columns: [
              {
                presenter: ->(comment) { link_to comment, comment },
                order_by: :id
              },
              :body,
              :created_at
            ],
            search_fields: %w(body)
end
```

**Comment by jpatel** [comment]
Thanks @jasondew.

I am using rails 4.1. I will try next branch and see if it works for me.

Thank you.

**Comment by jasondew** [comment]
@jpatel Happy to help!
