### ISSUE TITLE
Rails5 - params no longer inherits from HashWithIndifferentAccess 

### ISSUE THREAD

**Issue by scottbarrow** [jasondew/data_table#18]
issue:
```undefined method `map' for #<ActionController::Parameters```

https://github.com/jasondew/data_table/blob/master/lib/data_table/base.rb#L10
calls `controller.params.map`. 
In Rails 5+ params no longer inherits from HashWithIndifferentAccess. enumerable methods are not available on Strong param objects.

It might not be good enough to simply call `to_h` since any non permitted params will be excluded from the resulting hash.

**Comment by jasondew** [comment]
Hi @scottbarrow ! I'm not really using the library anymore but I'd be happy to review a PR to fix this if you have the time. If not, I'll try to have a look at some point. Either way, thanks for reporting the issue!

**Comment by scottbarrow** [comment]
well the library needs to be updated to support Rails strong params as opposed to expecting a naked params hash. If the params are not "permitted" the param values are not accessible. 

I don't know enough about the gem since I was only doing maintenance updates, however from what I can tell maybe it's better to send `data_table_params` so that the library only handles relevant and whitelisted params and have the `for_data_table` caller implement this method?

**Comment by scottbarrow** [comment]
awesome thanks, that should work
